[theme]
primaryColor = "#1e293b"
backgroundColor = "#f8f5f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c2c2c"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false